name: auto_rula
description: A starting point for Dart libraries or applications.
version: 1.0.11
repository: https://github.com/fhstp/auto_rula

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.0.0
  parameterized_test: ^2.0.1
  test: ^1.24.0
  very_good_analysis: ^8.0.0
dependencies:
  meta: ^1.16.0
  fast_immutable_collections: ^11.1.0
  vector_math: ^2.1.0
