name: auto_rula
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/fhstp/auto_rula

environment:
  sdk: ^3.7.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^8.0.0
